# Generated by Django 4.2.7 on 2025-02-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minutes_played', models.FloatField(default=0.0)),
                ('training_load', models.FloatField(default=0.0)),
                ('prev_injuries', models.IntegerField(default=0)),
            ],
        ),
    ]
