# Generated by Django 4.2.7 on 2025-02-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
